language: java

sudo: required

dist: trusty

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: mvn --version

script:
  - java -version
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean install
